<h3>商品列表</h3>
<template>
	<el-table
	:data="tableData3"
	border
	stripe
	tooltip-effect="dark"
	style="width: 100%"
	@selection-change="handleSelectionChange">
		<el-table-column
		  type="selection"
		  width="55">
		</el-table-column>
		<el-table-column
		  label="日期"
		  width="120">
		  <template scope="scope">{{ scope.row.date }}</template>
		</el-table-column>
		<el-table-column
		  prop="name"
		  label="姓名"
		  width="120">
		</el-table-column>
		<el-table-column
		  prop="address"
		  label="地址"
		  show-overflow-tooltip>
		</el-table-column>
	</el-table>
</template>